### PR TITLE
Update gitignore to ignore generated files in src/

### LINKED ISSUE #185: Add built files to .gitignore
#183 changes 6 lines and has a 500+ line diff

### PR DESCRIPTION
**Pull request by MaxLeiter**
Closes #185

### CODE REVIEW

**Comment by MaxLeiter** [comment]
bump, @ritz078 ?

**Comment by ritz078** [comment]
I am just figuring out a better way to do this. removing build files totally from that folder and putting them inside specific folders that can be excluded from git.

**Comment by MaxLeiter** [comment]
It's probably also worth setting up an npm prepublish command so similar files are ignored until published to npm

**Comment by ritz078** [comment]
Few things:
* dist folder is needed by cdnjs
* even if we try to remove it we need task in prepublish

This will take some time as will need to refactor the folder structure.

**Comment by MaxLeiter** [comment]
just an fyi, this PR doesn't change the dist folder

**Comment by ritz078** [comment]
i know that. I will just change the folder structure and write prepublish scripts so the dists get created before publish.

**Comment by ritz078** [comment]
fixed in master

**Pull request closed without merging**
