### PR TITLE
UMD support added

### PR DESCRIPTION
**Pull request by jesusprubio**
Implemented following the [UMD recommendations for jQuery plugins](https://github.com/umdjs/umd/blob/master/jqueryPluginCommonjs.js).

Moreover I've added the "resources" folder to have a common root folder for all the resources.

Thanks! The library really rocks!  :+1:

### CODE REVIEW

**Comment by ritz078** [comment]
Thanks a lot . Really useful enhancement. :+1:

**Comment by ritz078** [comment]
added you as a contributor :smile:

**Comment by jesusprubio** [comment]
Thanks, I'll playing these next days with it at work, so you'll know more about me. :)

**Comment by ritz078** [comment]
Would love to know more about you :)

**Pull request merged**
