### PR TITLE
Add imageOptions with maxWidth and maxHeight

### PR DESCRIPTION
**Pull request by MaxLeiter**

### CODE REVIEW

**Comment by ritz078** [comment]
You already have the class name. I prefer it to be set by CSS.

**Comment by MaxLeiter** [comment]
Should it be added for consistency? You have similar options for tweets and vines

**Comment by ritz078** [comment]
That is because they need the dimensions while making a request and can't be later changed using CSS. For others CSS should be simple. I think if I add dimensions by JS it will always override CSS that's not preferable. Any use case that is effected ?

**Comment by MaxLeiter** [comment]
On [TheLounge](https://www.github.com/thelounge/lounge), we may want different sizes for different images (and may have multiple EmbedJS instances)

**Comment by ritz078** [comment]
how are you deciding the image sizes ?

**Comment by MaxLeiter** [comment]
After some thought, I see your point.

**Pull request closed without merging**
