### PR TITLE
Never and ever pollute Array/String prototype

### PR DESCRIPTION
**Pull request by ibc**
Remove custom methods from the `Array` / `String` prototype. There are tons of libraries out there relying on "bad" array iterations (`for(var item in array) { ... }`) and they get broken if any other library (embed.js) adds stuff into the prototype of `Array` or `String`.

Sometimes it is not possible to fix it (for example when you develop a widget that must co-exist in 3rd party web sites which are not under your control), so leaving the prototype clean is the proper way to go.

This commit fixes https://github.com/ritz078/embed.js/issues/42.

### CODE REVIEW

**Comment by ritz078** [comment]
thanks for the PR :)

**Comment by ibc** [comment]
Thanks to you!
May I know when embed-js 2.0.6 will be available in NPM?

**Comment by ritz078** [comment]
I have updated it . You can get it now .

**Comment by ibc** [comment]
Really thanks!

**Pull request merged**
